---
title: JPE Replication Report
date: today
number-sections: true
format:
  html: default
---

# Paper Identification

|           |                      |
|-----------|----------------------|
| ID        | {{< var paper_id >}} |
| Author    | {{< var author >}}   |
| Title     | {{< var title >}}    |
| Iteration | {{< var round >}}    |

Some useful information up front:

-   [JPE Data and Code Availability Policy](https://www.journals.uchicago.edu/journals/jpe/datapolicy)
-   [Step by step guidance from Data Editor for Authors](https://jpedataeditor.github.io/)
-   [Template README](https://social-science-data-editors.github.io/template_README/)

# Summary

In assessing compliance with our [Data and Code Availability Policy](https://www.journals.uchicago.edu/journals/jpe/datapolicy), our reproducibility team has identified the following issues, which we ask you to address:

1.  We will schedule a remote replication session.
2.  There are a few small things to fix. Please resubmit and we take it from there.

# General

-   [x] Data Availability and Provenance Statements
    -   [x] Statement about Rights - Part 1: Right to use the data (e.g. *did the authors lawfully obtain the data*)
    -   [ ] Statement about Rights - Part 2: Right to publish the data (e.g. *are human subjects involved and did permission been granted to publish their data?*)
    -   [ ] License for Data (optional, but recommended)
    -   [x] Details on each Data Source
-   [ ] Dataset list
-   [x] Computational requirements
    -   [x] Software Requirements
    -   [ ] Controlled Randomness (as necessary)
    -   [x] Memory, Runtime, and Storage Requirements
-   [x] Description of programs/code
    -   [x] License for Code (Optional, but recommended)
-   [x] {REPLICATOR} to Replicators
    -   [x] Details (as necessary)
-   [ ] List of tables and programs
-   [x] References (Optional, but recommended)

# High-level Description of Research Project

*This research project...*

-   [ ] uses observational data.
-   [x] uses *confidential* observational data.
-   [ ] uses data generated via experiment or trial by the authors (in field or lab).
    -   [ ] For lab experiments: The code to implement the experimental protocol (z-Tree, o-Tree etc) is included in the package.
    -   [ ] A PDF copy of IRB approval is contained in the package.
    -   [ ] A PDF document outlining the design of the experiment, including information on the selection and eligibility of participants is included.
    -   [ ] A PDF copy of the instructions given to participants in both original language and an English translation is included.
-   [ ] uses data generated via survey by the authors (in field or online)
    -   [ ] The programs used to administer the survey (e.g. qualtrics survey file) are included.
    -   [ ] A PDF copy of IRB approval is contained in the package.
    -   [ ] A PDF of the original questionaire(s) and information on the selection and eligibility of participants is included.
-   [ ] is a simulation study: the data are generated by an algorithm.
-   [ ] is a numerical illustration: no data are used but code is used to produce illustrative output (tables, figures)

# Data description

For any data that cannot be provided as part of the replication package, please provide the following information as part of the README.

> {REQUIRED} Please specify how long the data will be preserved in the restricted-access location.

> {REQUIRED} Please provide affirmation of support for replication checks. - As per the [JPE policy](https://jpedataeditor.github.io/policy.html), "In cases where data cannot be published in an openly accessible trusted data repository like the JPE dataverse, authors who have requested an exemption to publish them at the time of first submission must commit to preserving the data and code for a period of no less than five years following the publication of the paper. They should also provide reasonable assistance to requests for clarification and replication."

> {REQUIRED} Please provide a codebook for the data. - The codebook should at a minimum describe the variables obtained from the data source, in a manner that will let others verify that they have obtained a substantially similar dataset if successfully obtaining access to the data.

## Data Sources

| file/name | public | private | DOI/URL | Access described | cited readme | cited paper |
|-----------|-----------|-----------|-----------|-----------|-----------|-----------|
| IPUMS USA complete count (1880–1930) | yes | no | yes | yes | yes | yes |
| Haines (2010), ICPSR 02896 | yes | no | yes | no | yes | yes |
| ICPSR 00001 (elections) | no | no | yes | no | no | no |
| IPUMS restricted full-count with surnames | no | yes | yes | yes | yes | yes |
| Union proceedings | yes | no | no | no | no | no |
| Gregory (2015), IWW History Project | yes | no | yes | no | yes | yes |
| Garlock (2009) / KoL, ICPSR 00029 | no | yes | yes | no | yes | yes |
| Fed. Reserve Bank of Minneapolis, CPI | yes | no | yes | no | yes | no |
| Migration Policy Institute | yes | no | yes | no | yes | no |
| Willcox (1929) | yes | no | no | no | yes | yes |
| Freeman (1998), NBER WP 6012 | yes | no | yes | no | yes | yes |
| Ferrara et al. (2022), ICPSR 150101 | yes | no | yes | no | yes | yes |
| IPUMS NHGIS, 1930 county shapefile | yes | no | no | no | yes | yes |
| Day (1892), mineral industries | yes | no | no | no | yes | yes |
| Atack (2016), railroad GIS | yes | no | yes | yes | yes | yes |
| Farber et al (2021), Weather_Data.dta | yes | no | no | no | no | yes |
| Sequeira et al (2020), unionshares.dta | yes | no | no | no | no | yes |

# Requirements

-   [x] README is in TXT, MD, or PDF format
-   [x] README is accessible at the root of the package (not inside a folder)
-   [ ] Title conforms to guidance (starts with "Data and Code for: Title of Paper" or "Code for: Title of Paper", is properly capitalized)
-   [x] Authors (with affiliations) are listed in the same order as on the paper

> {REQUIRED} Please review the title of the deposit as per our guidelines.

## Stated Requirements

-   [ ] No requirements specified
-   [x] Software Requirements specified as follows:
    -   Stata 19.5
-   [x] Computational Requirements specified as follows:
    -   Windows Server 2022 Standard (Version 21H2), 64-bit operating system, Intel(R) Xeon(R) Gold 6426Y 2.50 GHz (2 processors), 1TB RAM.
-   [x] Time Requirements specified as follows:
    -   12.5 hours
-   [ ] Requirements are complete.

For missing requirements, see the list of required changes in @sec-findings

# Analyzing Data and Code Files

{{< include generated/report-pii.md >}}

{{< include generated/report-file-paths.md >}}

{{< include generated/report-duplicates.md >}}

{{< include generated/report-zero-files.md >}}

{{< include generated/report-large-files.md >}}

## Code description

There are 16 `.do` files, one of which is the master.

{{< include generated/report-cloc.md >}}

-   [x] The replication package contains a "main" or "master" file(s) which calls all other auxiliary programs.

## Computing Environment of the Replicator

-   Nuvolos: Ubuntu 24.04.1 LTS, 16 vCPU + 64 GB RAM

-   Stata/MP 19.5

# Replication

-   Downloaded code and data from dropbox.
-   Copied git repo and unzipped the replication package into this repo.
-   Adjusted the root of the `00_Master.do` as per `README.md`
-   Ran code as per README. Code broke because of missing packages `shp2dta`. Ran again.
-   Code broke because of missing raw dataset `Weather_Data.dta`. As explained in the `README.md`, the master Do file should have run without problems since all re-distributable datasets were contained in the folder `data/public`. However, it does not seem to be the case. The error outputted by Stata was the following

```         
. use "$rawlocal/Replication_Sequeira_et_al_2020/Weather_Data.dta", clear
file /files/JPE-Medici-20241468/replication-package/MS20241468_Deposit/data/_raw_local/Replication_Sequeira_et_al_2020/Weather_Data.dta not
    found
r(601);
```

-   Tried to run `1f_shiftshare.do` standalone, but a new issue of intermediate dataset arised:

```         
. *Merge predicted immigrant flows (based on weather)
. merge m:1 year using "$intmdata/predicted_flows_weather.dta"
file /files/JPE-Medici-20241468/replication-package/MS20241468_Deposit/data/intermediate/predicted_flows_weather.dta not found
r(601);
```

-   Tried to run `1h_final_dataset.do` standalone, but a new issue arised regarding final dataset for analysis:

```         
. merge 1:1 year countynhg_1930 using "$data/shiftshare_county1930.dta"
file /files/JPE-Medici-20241468/replication-package/MS20241468_Deposit/data/clean/shiftshare_county1930.dta not found
r(601);
```

-   Removed old output in the folders `output/tables` and `output/figures` and left only the replicated one.

# Findings {#sec-findings}

## Missing Requirements

-   [x] Software Requirements
    -   [x] Stata
        -   [x] Missing packages in the `00_master.do`: geoinpoly, shp2dta
        -   [x] Version of Stata packages
-   [x] Computational Requirements specified as follows:
    -   [x] Missig needed hard-disk memory (at least 9 GB from what I could replicate)
-   [ ] Time Requirements
    -   Length of necessary computation (hours, weeks, etc.)

> \[REQUIRED\] Please amend README to contain complete requirements.

## Data Preparation Code

-   Only `1a_reference_inputs.do`, `1b_merge_preadjust.do`, `1c_boundary_adjustment.do`, `1d_county_panel.do`, `1g_crowdout.do`, `2b_figures_descriptives.do`, `2e_results_robustness.do` ran without breaking but the only output obtained consists of 2 figures listed below.

## Tables and Figures {#sec-output}

| Figure/Table \# | Program                    | Line Number | Reproduced? |
|-----------------|----------------------------|-------------|-------------|
| Figure 1        | 2b_figures_descriptives.do | 66          | yes         |
| Figure 2        | 2a_sumstats.do             | 50          | no          |
| Figure 3        | 2e_results_robustness.do   | 1536        | no          |
| Figure 4        | 2e_results_robustness.do   | 229         | no          |
| Figure 5        | 2a_sumstats.do             | 427         | no          |
| Table 1         | 2a_sumstats.do             | 155         | no          |
| Table 2         | 2c_results_main.do         | 42          | no          |
| Table 3         | 2c_results_main.do         | 80          | no          |
| Table 4         | 2c_results_main.do         | 205         | no          |
| Table 5         | 2c_results_main.do         | 289         | no          |
| Table 6         | 2c_results_main.do         | 342         | no          |
| Table 7         | 2c_results_main.do         | 484         | no          |
| Table 8         | 2c_results_main.do         | 560         | no          |
| Figure A.1      | 2b_figures_descriptives.do | 40          | yes         |
| Figure A.4      | 2a_sumstats.do             | 285         | no          |
| Figure A.5      | 2c_results_main.do         | 808         | no          |
| Figure G.1      | 2f_rotemberg_weights.do    | 254         | no          |
| Figure H.1      | 2a_sumstats.do             | 355         | no          |
| Table A.2       | 2a_sumstats.do             | 199         | no          |
| Table A.3       | 2a_sumstats.do             | 236         | no          |
| Table A.4       | 2d_results_extra.do        | 38          | no          |
| Table A.5       | 2c_results_main.do         | 409         | no          |
| Table A.6       | 2c_results_main.do         | 759         | no          |
| Table A.7       | 2c_results_main.do         | 858         | no          |
| Table A.8       | 2d_results_extra.do        | 94          | no          |
| Table A.9       | 2d_results_extra.do        | 149         | no          |
| Table A.10      | 2d_results_extra.do        | 210         | no          |
| Table A.11      | 2d_results_extra.do        | 278         | no          |
| Table B.2       | 2e_results_robustness.do   | 44          | no          |
| Table G.1       | 2f_rotemberg_weights.do    | 196         | no          |
| Table G.2       | 2e_results_robustness.do   | 44          | no          |
| Figure B.2      | 2e_results_robustness.do   | 221         | no          |
| Figure B.1      | 1e_weather_shocks.do       | 189         | no          |
| Table B.1       | 2e_results_robustness.do   | 1137        | no          |
| Table A.1       | /                          |             |             |
| Figure A.2      | /                          |             |             |
| Figure A.3      | /                          |             |             |
| Table E.1       | ?                          |             | no          |
| Table F.1       | ?                          |             | no          |

## In-Text Numbers

| In-text numbers | Program | Line Number | Reproduced? |
|-------------------------|----------------|----------------|----------------|
| p.3 & 39: "in the absence of immigration, union density 1900-1920 would have been \~22% lower" (also \~31% for skilled) | 2c_results_main.do | 195–197 | No |

-   [ ] In-text numbers not verified.

-   [ ] There are no in-text numbers, or all in-text numbers stem from tables and figures.

-   [x] There are in-text numbers, but they are not identified in the code

## Other Issues

-   It is possible that in the notes of Figure 1 there is a typo in the source of the immigrants inflow where it says 'Immigration Policy Institute' while it should be 'Migration Policy Institute' as cited in `README.md`

-   `README.md` did not enlist raw data but rather intermediate datasets and their sources. Even though they are not shipped in the package, it is important to cite them as if they were included.

-   `README.md` did not include a list of output elements and which scripts produced them. I provided a list in the section @sec-output

# Classification

-   [ ] full reproduction
-   [ ] full reproduction with minor issues
-   [ ] partial reproduction (see above)
-   [x] not able to reproduce most or all of the results (reasons see above)

## Reason for incomplete reproducibility

-   [ ] None.
-   [ ] `Discrepancy in output` (either figures or numbers in tables or text differ)
-   [ ] `Bugs in code` that were fixable by the replicator (but should be fixed in the final deposit)
-   [ ] `Code missing`, in particular if it prevented the replicator from completing the reproducibility check
    -   [ ] `Data preparation code missing` should be checked if the code missing seems to be data preparation code
-   [ ] `Code not functional` is more severe than a simple bug: it prevented the replicator from completing the reproducibility check
-   [ ] `Software not available to replicator` may happen for a variety of reasons, but in particular (a) when the software is commercial, and the replicator does not have access to a licensed copy, or (b) the software is open-source, but a specific version required to conduct the reproducibility check is not available.
-   [ ] `Insufficient time available to replicator` is applicable when (a) running the code would take weeks or more (b) running the code might take less time if sufficient compute resources were to be brought to bear, but no such resources can be accessed in a timely fashion (c) the replication package is very complex, and following all (manual and scripted) steps would take too long.
-   [x] `Data missing` is marked when data *should* be available, but was erroneously not provided, or is not accessible via the procedures described in the replication package
-   [ ] `Data not available` is marked when data requires additional access steps, for instance purchase or application procedure.
-   [ ] `Missing README` is marked if there is no README to guide the replicator, or the README is not in compliance with JPE requirements

{{< include generated/report-pii.md >}}
